font:
  size: 12.0
  normal:
    family: CodeNewRoman Nerd Font
    style: Book
  bold:
    family: CodeNewRoman Nerd Font
    style: Bold
  italic:
    family: CodeNewRoman Nerd Font
    style: Italic
  bold_italic:
    family: CodeNewRoman Nerd Font
    style: Bold Italic