---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Safari
  - Launchpad
  - Mail
  - TV
  - Podcasts
  - 'App Store'
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Music
  - 'System Settings'
  - Keynote
  - Numbers
  - Pages
  - 'App Store'
dockitems_persist:
  - name: "Thunderbird"
    path: "/Applications/Thunderbird.app/"
    pos: 3
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 4
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 5
  - name: "iTerm2"
    path: "/System/Applications/iTerm2.app/"
    pos: 6
  - name: "VSCodium"
    path: "/Applications/VSCodium.app/"
    pos: 7
  - name: "Notes"
    path: "/Applications/Notes.app/"
    pos: 8
  - name: "Reminders"
    path: "/Applications/Reminders.app/"
    pos: 9
  - name: "Spotify"
    path: "/Applications/Spotify.app/"
    pos: 10
  - name: "KeePassXC"
    path: "/Applications/KeePassXC.app/"
    pos: 11
  - name: "Signal"
    path: "/Applications/Signal.app/"
    pos: 12
  - name: "Telegram Desktop"
    path: "/Applications/Telegram Desktop.app/"
    pos: 13
  - name: "TextEdit"
    path: "/System/Applications/TextEdit.app/"
    pos: 14
  - name: "LibreOffice"
    path: "/Applications/LibreOffice.app/"
    pos: 15
  - name: "Calendar"
    path: "/Applications/Calendar.app/"
    pos: 16
  - name: "Contacts"
    path: "/Applications/Contacts.app/"
    pos: 17

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/axkng/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/git/dev/dotfiles
dotfiles_repo_version: main
dotfiles_files:
  - .gitconfig
  - .zshrc
  - .gitignore
  - .osx

homebrew_installed_packages:
  - ssh-copy-id
  - wget
  - terraform
  - fzf
  - Kubernetes-cli
  - curl
  - telnet
  - awscli
  - tmux
  - krew
  - helm
  - pwgen
  - watch
  - gnu-sed
  - jq
  - nmap
  - rclone
  - pidof
  - k9s
  - dockutil
  - qrencode
  - bat
  - exa
  - dust
  - ripgrep
  - procs
  - fd
  - sd
  - starship
  - gpg
  - s3cmd

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - google-chrome
  - signal
  - nextcloud
  - telegram-desktop
  - spotify
  - vscodium
  - thunderbird
  - keepassxc
  - font-code-new-roman-nerd-font
  - iterm2
  - rectangle
  - libreoffice
  - balenaetcher

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1451685025, name: "WireGuard" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - name: netaddr
    state: present

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
